### ISSUE TITLE
Prettier 3.0 

### ISSUE THREAD

**Issue by mattbrannon** [idahogurl/vs-code-prettier-eslint#171]
Prettier just [released a new major version](https://prettier.io/blog/2023/07/05/3.0.0.html) which includes some breaking changes to the API. Currently Prettier 3.0 causes the extension to throw a type error:

```
Error: Expected `input` to be a `string`, got `object` 
TypeError: Expected `input` to be a `string`, got `object`
```

I haven't looked into the source code for Prettier or this extension for a while so I don't know how difficult of a fix this is.

If anyone is having this same issue, the short term solution is to explicitly install a version of prettier before 3.0.
```bash
npm i -D prettier@2.8.8
```

**Comment by mattbrannon** [comment]
More info [in this PR](https://github.com/prettier/prettier-eslint/pull/901#issue-1793138799)

**Comment by Catatomik** [comment]
Any update on this ?
Is there a roadmap ?

**Comment by zhangjie1314** [comment]
Please fix it, thank you.

**Comment by PrinceGuidon** [comment]
Any update on this?

**Comment by danielwerg** [comment]
https://github.com/prettier/prettier-eslint/pull/901 just got merged.

**Comment by arange** [comment]
Any update? Much appreciated

**Comment by maxkostow** [comment]
Seems like this should be fixed by #187

**Comment by idahogurl** [comment]
Sorry for the lack of response. I've been dealing with medical issues in addition to everything else. Someone created a PR to update everything #189 but it needs some changes and I don't have the time resources to help. Also, the automated deploy isn't working and could use some help there.

**Comment by idahogurl** [comment]
I did a little testing of #189 and upgrading to Prettier 3 is not an option at this time. I am getting the same error as https://github.com/prettier/prettier-vscode/issues/3114 describes when I try to run my extension. Prettier 3 added an EcmaScript Module (ESM) import and VS Code does not support ESM, only CommonJS (CJS). Basically we are stuck with Prettier 2.

**Comment by KillDozerX2** [comment]
> Sorry for the lack of response. I've been dealing with medical issues in addition to everything else. Someone created a PR to update everything (#189) but it needs some changes and I don't have much time to help. Also, the automated deploy isn't working and could use some help there.

Do you still need help resolving automated deploys?

**Comment by idahogurl** [comment]
@KillDozerX2 I do still need help with automated deploys. I'm using Auto ([docs](https://intuit.github.io/auto/docs)) to automate the deploys. I think I have it setup wrong.  When I run the [release workflow]( https://github.com/idahogurl/vs-code-prettier-eslint/actions/workflows/release.yml) it should see there is a new version and publish the extension, but it doesn't. Here is their example: https://intuit.github.io/auto/docs/build-platforms/github-actions

I think it only works with this workflow: https://intuit.github.io/auto/docs/generated/shipit#release-pipeline

**Comment by JounQin** [comment]
I would recommend to migrate to [`changesets`](https://github.com/changesets/changesets) instead.

And it maybe great to migrate this repo into the `prettier` org just like `prettier-eslint`, how do you think?

**Comment by 0x2aff** [comment]
I created something based on your work @idahogurl.
The key was to use `worker_threads`. Prettier is doing this as well for their VSCode extension.

(https://github.com/0x2aff/vscode-prettier-eslint)
(https://marketplace.visualstudio.com/items?itemName=exceptionptr.vscode-prettier-eslint)

**Comment by idahogurl** [comment]
@0x2aff I actually tried using worker threads as well but it wasn't applying the Prettier config in my tests. I'll have to try your code and see if I can't get my tests to pass.

**Comment by idahogurl** [comment]
@0x2aff I tried your extension and it has the same problem with my test file. I'll create an issue in your repository and provide the files needed to reproduce.

**Comment by DucNg** [comment]
> I do have a beta version of the extension working with Prettier 3. It has some breaking changes:
> 
>     * `prettier-eslint` is now required as a dev dependency
> 
>     * Prettier v3.0 is now required
> 
>     * ESLint >= v8.52.0 is now required
> 
> 
> Download and install the extension from here: [vs-code-prettier-eslint-6.0.0-beta.vsix.zip](https://github.com/idahogurl/vs-code-prettier-eslint/files/13531253/vs-code-prettier-eslint-6.0.0-beta.vsix.zip)
> 
> Once I have enough people testing it, I will making it available as a general release. Let me know if you find any issues with it.

Thanks a lot!

I just tried and I got this error from the extension output:

```
Error: Cannot find module 'prettier-eslint'
Require stack:
- /home/duc/.vscode/extensions/rvest.vs-code-prettier-eslint-6.0.0-beta/dist/extension.js
- /opt/visual-studio-code/resources/app/out/vs/loader.js
- /opt/visual-studio-code/resources/app/out/bootstrap-amd.js
- /opt/visual-studio-code/resources/app/out/bootstrap-fork.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:15)
    at Function.s._resolveFilename (node:electron/js2c/utility_init:2:2786)
    at Function.h.resolve (/opt/visual-studio-code/resources/app/out/vs/loader.js:4:709)
    at Gt (/home/duc/.vscode/extensions/rvest.vs-code-prettier-eslint-6.0.0-beta/dist/extension.js:1:6854)
    at /home/duc/.vscode/extensions/rvest.vs-code-prettier-eslint-6.0.0-beta/dist/extension.js:1:7526
    at Generator.next (<anonymous>)
    at /home/duc/.vscode/extensions/rvest.vs-code-prettier-eslint-6.0.0-beta/dist/extension.js:1:791
    at new Promise (<anonymous>)
    at b (/home/duc/.vscode/extensions/rvest.vs-code-prettier-eslint-6.0.0-beta/dist/extension.js:1:611)
    at qt (/home/duc/.vscode/extensions/rvest.vs-code-prettier-eslint-6.0.0-beta/dist/extension.js:1:6888)
    at Object.provideDocumentRangeFormattingEdits (/home/duc/.vscode/extensions/rvest.vs-code-prettier-eslint-6.0.0-beta/dist/extension.js:2:299)
    at q.provideDocumentRangeFormattingEdits (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:47266)
    at /opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:71002
    at be.s (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:65353)
    at be.$provideDocumentRangeFormattingEdits (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:70989)
    at n.S (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10836)
    at n.Q (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10602)
    at n.M (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:9647)
    at n.L (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:8762)
    at h.value (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:7565)
    at c.y (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at c.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at d.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14047)
    at h.value (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:7918)
    at c.y (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at c.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at d.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14047)
    at MessagePortMain.<anonymous> (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:6198)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain.emit (node:domain:489:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

**Comment by netux** [comment]
> Download and install the extension from here: [vs-code-prettier-eslint-6.0.0-beta.vsix.zip](https://github.com/idahogurl/vs-code-prettier-eslint/files/13531253/vs-code-prettier-eslint-6.0.0-beta.vsix.zip)
> 
> Once I have enough people testing it, I will making it available as a general release. Let me know if you find any issues with it.

Thank you! I tested on a medium-sized real-world project. The new version seems to work great, although its noticeably slower than the original. I assume the bottleneck is with the worker communication?

**Comment by idahogurl** [comment]
@netux Yes, the bottleneck is using worker threads.

**Comment by idahogurl** [comment]
@JounQin It looks like I can't use `synckit` because it wants `ts-node` or `tsx` to run the worker process. Would https://github.com/lambci/sync-threads be faster than recreating the worker each time?

**Comment by JounQin** [comment]
> it wants ts-node or tsx to run the worker process

No, it doesn't, if the worker is plain js, then js will be used. No ts runner required.

> Would [lambci/sync-threads](https://github.com/lambci/sync-threads) be faster than recreating the worker each time?

No, see benchmark https://github.com/un-ts/synckit/blob/main/benchmarks/benchmark.cjs.txt and https://github.com/un-ts/synckit/blob/main/benchmarks/benchmark.esm.txt

**Comment by idahogurl** [comment]
@netux Could you try this version to see if it speeds things up. It uses `synckit` as suggested by @JounQin 
[vs-code-prettier-eslint-6.0.0-beta.1.vsix.zip](https://github.com/idahogurl/vs-code-prettier-eslint/files/13621102/vs-code-prettier-eslint-6.0.0-beta.1.vsix.zip)

**Comment by jaschaephraim** [comment]
@idahogurl I've tried both beta versions. Now only the first run takes as long as the previous version, after that it's nearly instant. Thanks so much for your great work

**Comment by netux** [comment]
> @netux Could you try this version to see if it speeds things up? It uses `synckit` as suggested by JounQin [vs-code-prettier-eslint-6.0.0-beta.1.vsix.zip](https://github.com/idahogurl/vs-code-prettier-eslint/files/13621102/vs-code-prettier-eslint-6.0.0-beta.1.vsix.zip)

I can confirm what @jaschaephraim observed: the first format takes ~2.5 seconds, then subsequent formats are pretty much instant.

I think this could be improved even further if the worker was created on load. But as it is right now it feels pretty good for normal use. Thank you!

**Comment by JounQin** [comment]
> I think this could be improved even further if the worker was created on load.

Yep, the worker can be preloaded

**Comment by mattbrannon** [comment]
@idahogurl The latest beta version works great for me. I'm not seeing any noticeable delay when formatting.

**Comment by idahogurl** [comment]
@netux @jaschaephraim Try this version. I preloaded the worker.
[vs-code-prettier-eslint-6.0.0-beta.2.vsix.zip](https://github.com/idahogurl/vs-code-prettier-eslint/files/13622585/vs-code-prettier-eslint-6.0.0-beta.2.vsix.zip)

**Comment by jaschaephraim** [comment]
@idahogurl beta 2 performs just like beta 1, still a short delay on the first run only

**Comment by idahogurl** [comment]
@jaulz All I can think of is having you restart VS Code and creating a minimal reproduction project.

**Comment by Jmyerzzz** [comment]
what versions of `prettier` and `prettier-eslint` can I downgrade to to restore format on save functionality?

**Comment by uberubert** [comment]
I've been struggling with lack of format on save all day and haven't found a solution. I'll just add my +1.

**Comment by idahogurl** [comment]
@Jmyerzzz @uberubert Format on save should be working. Can you provide further information as to exactly isn't working and perhaps a minimal reproduction project. Also, what version of VS Code are you running. I've been using the beta for a while now and haven't had issues.

**Comment by JU12000** [comment]
@idahogurl Using beta 1 at the moment in a mid-sized monorepo and not seeing any issues with formatting. However if I change my prettier or eslint config files I have to reload VSCode in order for the extension to pick up the changes and format properly again. Otherwise it works great, thank you for maintaining this extension 👍.

**Comment by Jmyerzzz** [comment]
@idahogurl 

VSCode v1.85.1
prettier v3.1.1
prettier-eslint v16.1.2

Output:
TypeError: Expected `input` to be a `string`, got `object`

**Comment by idahogurl** [comment]
@netux @jaschaephraim Please try this new version to see if it speeds things up
[vs-code-prettier-eslint-6.0.0-beta.3.vsix.zip](https://github.com/idahogurl/vs-code-prettier-eslint/files/13678236/vs-code-prettier-eslint-6.0.0-beta.3.vsix.zip)

**Comment by jaschaephraim** [comment]
Still seeing the same short delay on the first format, very fast after that.

**Comment by ibussieres** [comment]
I've been using beta2 all morning, It seems to be working fine! I'll be using it daily, so unless I report back, it's safe to assume  that it's working well for me.

    "eslint": "^8.52.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.1.2",
    "prettier": "^3.1.1",
    "prettier-eslint": "^16.2.0",

**Comment by jinsley8** [comment]
If you go to vscode settings and find `Prettier: Prettier Path` option, make sure this is empty.

My vscode keeps adding it back somehow then `prettier` stops working again.

**Comment by JounQin** [comment]
@novarolV I don't think you're using the correct version.

https://github.com/idahogurl/vs-code-prettier-eslint/pull/199/files#diff-c388369e05210ed3a6e99d95fe34f9fb8019623852f71d478bb88e06dbb84fd5

**Comment by JounQin** [comment]
@novarolV Can you help to test via PR based of https://github.com/idahogurl/vs-code-prettier-eslint/pull/199/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R55

**Comment by robertheessels** [comment]
Beta 3 works great in my project. Thank you!

**Comment by phun-ky** [comment]
@idahogurl you are doing an awesome job here <3 

Do we have any eta? Stay well!

**Comment by idahogurl** [comment]
@phun-ky @ozyx It's been released. Make sure to install the `prettier-eslint` package or else it won't work :)

**Comment by ozyx** [comment]
> @phun-ky @ozyx It's been released.

You're awesome! Thanks!

**Comment by JounQin** [comment]
@idahogurl The v6 tag/release is missing.

**Comment by robertheessels** [comment]
Works great. Thank you!
